### ISSUE TITLE
Required parameter is missing: contact

### ISSUE THREAD

**Issue by StasPonomaryov** [webasyst/shop-script#336]
Работает ли метод API shop.order.add?

Воспроизвести:

`https://<SITE_URL>/api.php/shop.order.add`

```
Authorization: Bearer <TOKEN>
Content-Type: application/json
```

```
{
  "contact": {
    "firstname": "Іван",
    "lastname": "Іванов",
    "email": "ivanov@example.com",
    "phone": "+380123456789"
  },
  "items": [
    {
      "product_id": "123",
      "sku_id": "456",
      "quantity": 1,
      "price": 100
    }
  ],
  "shipping_id": "1",
  "payment_id": "2",
  "comment": "Доставка до дверей",
  "total": 100,
  "debug": true
}
```

получаем ответ:

```
{
    "error": "invalid_param",
    "error_description": "Required parameter is missing: contact"
}
```

если этот метод не поддерживается, то планируется ли его доработка?

**Comment by Leonix** [comment]
Кажется, в данном случае проблема в формате данных. API ШС не умеет принимать JSON, нужен `www-form-urlencoded` или `multipart/form-data`.

**Comment by StasPonomaryov** [comment]
Да, прошу прощения

**Comment by avkosorotov** [comment]
Добрый день!

Нами принято решение отказаться от технической поддержки по электронной почте. Обращайтесь к нам через мессенджеры или онлайн-чат: кнопки есть на нашем сайте https://creativit.ru или на сайте-визитке https://button.amocrm.ru/drrlcl

С уважением, техподдержка компании «Креатив IT»
